name: CI.yml

on:
  pull_request:

jobs:
  client-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 11 && Maven Cache
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Build and run Client tests
        working-directory: client
        run: mvn -B clean test

  server-unit-tests:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Java 11 && Maven Cache
          uses: actions/setup-java@v4
          with:
              distribution: 'temurin'
              java-version: '11'
              cache: 'maven'

        - name: Build and run Server tests
          working-directory: zookeeper
          run: mvn -B clean test

  integration-tests:
    runs-on: ubuntu-latest
    needs: [client-unit-tests, server-unit-tests]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 11 && Maven Cache
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Build Server JAR
        working-directory: zookeeper
        run: mvn -B clean package -DskipTests


      - name: Build and start services
        working-directory: zookeeper
        run: docker compose up -d --build

      #TODO: Add a wait step to ensure services are up before running tests

      - name: Build Integration Tests
        working-directory: client
        run: mvn -B clean test -DskipUnitTests -Pintegration-tests


      - name: Cleanup
        if: always()
        working-directory: zookeeper
        run: docker compose down


