name: CI.yml

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 11 && Maven Cache
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Build Server JAR
        working-directory: zookeeper
        run: mvn -B clean package -DskipTests


      - name: Build and start services
        working-directory: zookeeper
        run: docker compose up -d --build

      #TODO: Add a wait step to ensure services are up before running tests

      - name: Build and run Client tests
        working-directory: client
        run: mvn -B clean test


      - name: Cleanup
        if: always()
        working-directory: ./zookeeper
        run: docker compose down
