name: CI.yml

on:
  pull_request:

jobs:
  client-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 11 && Maven Cache
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Build and run Client tests
        working-directory: client
        run: mvn -B clean test -Dtest=TestStore

  server-unit-tests:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Java 11 && Maven Cache
          uses: actions/setup-java@v4
          with:
              distribution: 'temurin'
              java-version: '17'
              cache: 'maven'

        - name: Build and run Server tests
          working-directory: zookeeper
          run: mvn -B clean test

  integration-tests:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    needs: [client-unit-tests, server-unit-tests]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 11 && Maven Cache
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Build Server JAR
        working-directory: zookeeper
        run: mvn -B clean package -DskipTests


      - name: Build and start services
        working-directory: zookeeper
        run: docker compose up -d --build


      - name: Verify Raft servers are listening
        run: |
          echo "Checking if Raft servers are ready..."
          for port in 6001 6002 6003 6004 6005; do
            timeout 60 bash -c "until nc -z localhost $port; do echo 'Waiting for port $port...'; sleep 2; done"
            echo "✓ Port $port is ready"
          done

      - name: Run Integration Tests
        working-directory: client
        #TODO: Use MVN profiles instead of running specific test class
        run: mvn -B clean test -Dtest=IntegrationTest


      - name: Cleanup
        if: always()
        working-directory: zookeeper
        run: docker compose down


